export enum ServiceType {
    STANDARD = 'STANDARD',
    PREMIUM = 'PREMIUM',
    BUSINESS = 'BUSINESS',
    BUSINESS_AREA_SILENZIO = 'BUSINESS AREA SILENZIO',
    BUSINESS_SALOTTINO = 'BUSINESS SALOTTINO',
    EXECUTIVE = 'EXECUTIVE',
}